name: Run Python Script with Docker on Push

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install python3-docker
        run: sudo apt-get update && sudo apt-get install -y python3-docker

      - name: Run Python script in Docker container
        working-directory: python
        run: |
          # Run the script using the official Python image
          docker run --rm \
            -v ${{ github.workspace }}/python:/app \
            -w /app \
            python:3.12-slim \
            bash -c "pip install -r requirements.txt && python run.py"
