name: Run Python Script with Docker on Push

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install python3-docker
        run: cd app && sudo apt install python3-docker && sudo python run_docker.py